var app=angular.module("myApp",["ngRoute"]);
app.controller("studentcontroller",function($scope)
{
$scope.student=[{sname:"smith",course:"html"},{sname:"sneha",course:"css"}];
});
app.controller("coursecontroller",function($scope)
{
$scope.cources=["html","css","angularjs","bootstrab"];
});
app.config(function($routeProvider)
{
$routeProvider
.when("/student",
{
templateUrl:"student.html",
controller:"studentcontroller"
})
.when("/contactus",
{
templateUrl:"contactus.html",
controller:""
})
.when("/cources",
{
templateUrl:"cources.html",
controller:"coursecontroller"
})
.when("/home",
{
templateUrl:"home.html",
controller:""
})
.otherwise({
redirectTo:"/home"
});
});